//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BIA.ToolKit.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BIADemoLocalFolder {
            get {
                return ((bool)(this["BIADemoLocalFolder"]));
            }
            set {
                this["BIADemoLocalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool BIADemoGitHub {
            get {
                return ((bool)(this["BIADemoGitHub"]));
            }
            set {
                this["BIADemoGitHub"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompanyFilesGit {
            get {
                return ((bool)(this["CompanyFilesGit"]));
            }
            set {
                this["CompanyFilesGit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CompanyFilesLocalFolder {
            get {
                return ((bool)(this["CompanyFilesLocalFolder"]));
            }
            set {
                this["CompanyFilesLocalFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\...\\BIADemo")]
        public string BIADemoLocalFolderText {
            get {
                return ((string)(this["BIADemoLocalFolderText"]));
            }
            set {
                this["BIADemoLocalFolderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://.../_git/BIACompanyFiles")]
        public string CompanyFilesGitRepo {
            get {
                return ((string)(this["CompanyFilesGitRepo"]));
            }
            set {
                this["CompanyFilesGitRepo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\...\\BIACompanyFiles")]
        public string CompanyFilesLocalFolderText {
            get {
                return ((string)(this["CompanyFilesLocalFolderText"]));
            }
            set {
                this["CompanyFilesLocalFolderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("D:\\...\\MyRootProjectPath")]
        public string CreateProjectRootFolderText {
            get {
                return ((string)(this["CreateProjectRootFolderText"]));
            }
            set {
                this["CreateProjectRootFolderText"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CompanyName")]
        public string CreateCompanyName {
            get {
                return ((string)(this["CreateCompanyName"]));
            }
            set {
                this["CreateCompanyName"] = value;
            }
        }
    }
}
