  // BIAToolKit - Begin Partial Permission MaintenanceTeam
  MaintenanceTeam_Create = 'MaintenanceTeam_Create',
  MaintenanceTeam_Delete = 'MaintenanceTeam_Delete',
  MaintenanceTeam_List_Access = 'MaintenanceTeam_List_Access',
  MaintenanceTeam_Read = 'MaintenanceTeam_Read',
  MaintenanceTeam_Save = 'MaintenanceTeam_Save',
  MaintenanceTeam_Update = 'MaintenanceTeam_Update',
  MaintenanceTeam_Member_Update = 'MaintenanceTeam_Member_Update',
  MaintenanceTeam_Member_Delete = 'MaintenanceTeam_Member_Delete',
  MaintenanceTeam_Member_Create = 'MaintenanceTeam_Member_Create',
  MaintenanceTeam_Member_List_Access = 'MaintenanceTeam_Member_List_Access',
  MaintenanceTeam_View_AddTeamView = 'MaintenanceTeam_View_Add_TeamView',
  MaintenanceTeam_View_UpdateTeamView = 'MaintenanceTeam_View_Update_TeamView',
  MaintenanceTeam_View_SetDefaultTeamView = 'MaintenanceTeam_View_Set_Default_TeamView',
  MaintenanceTeam_View_AssignToTeam = 'MaintenanceTeam_View_Assign_To_Team',
  // BIAToolKit - End Partial Permission MaintenanceTeam